(define (even? x) 
    (= (remainder x 2) 0))

(define (fast-mult a b)
    (cond ((= b 0) 0)
          ((even? b) (fast-mult (+ a a) (/ b 2)))
          (else (+ a (fast-mult a (- b 1))))))

(newline)
(display "Enter a number: ")
(define a (read))
(display "Enter a multiplier: ")
(define b (read))

(display a)
(display " * ")
(display b)
(display " = ")
(display (fast-mult a b))
(newline)
