(define (bin-coeff row col)
    (cond ((or (= row 0) (= col 0) (= row col)) 1)
          (else (+ (bin-coeff (- row 1) (- col 1))
                   (bin-coeff (- row 1) col)))))

(define (display-row n)
  (define (column-iter i)
    (display (bin-coeff n i)) 
    (display "  ")
    (if (= i n)
        (newline)
        (column-iter (+ i 1))))
  (column-iter 0))

(define (display-pascal-triangle n)
  (define (display-iter i)
    (display-row i)
    (if (= i n)
        (newline)
        (display-iter (+ i 1))))
  (display-iter 0))

(newline)
(display-pascal-triangle 10)